name = "sbtc-yield-vault"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
VAULT_CONTRACT = "SP2QXPFF4M72QYZWXE7S5321XJDJ2DD32DGEMN5QA.sbtc-loop-vault"
OPERATOR_ADDRESS = "SP2QXPFF4M72QYZWXE7S5321XJDJ2DD32DGEMN5QA"
NETWORK = "mainnet"
